### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by Adityadn64** [elrizwiraswara/flutter_pos#2]
Pada hasil transaksi hasil pada Ordered Products selalu 0 dan dan informasi produk yang dibeli tidak muncul

`Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Ordered Products',
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.bold),
              ),
              Text(
                '${transaction.orderedProducts?.length ?? '0'}',
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.bold),
              )
            ],
          ),
          const Divider(height: AppSizes.padding * 2),
          ...List.generate(transaction.orderedProducts?.length ?? 0, (i) {
            return Padding(
              padding: EdgeInsets.only(top: i == 0 ? 0 : AppSizes.padding / 2),
              child: product(context, transaction.orderedProducts![i]),
            );
          }),`
          
![transaction_1722580529943](https://github.com/user-attachments/assets/06f1913c-1863-4691-935a-6a8529592cf9)

**Comment by elrizwiraswara** [comment]
Hi [Adityadn64](https://github.com/Adityadn64)

Have you tried it again with the latest version/commit? Because that bug should have been fixed in the latest version.

**Comment by Adityadn64** [comment]
sudah, tapi ketika saya anlisis lagi ada yang aneh, ketika di device 1 saya membuat transaksi didalam transaksi tersebut menunjukkan data ordered product tidak 0 dan data pada `Widget product(BuildContext context, OrderedProductEntity order)` tampil, tetapi ketika saya lihat di device 2 transaksi tersebut terjadi bug seperti tampilan diatas, mungkin disebabkan karena data ordered product dan product yang dipesan hanya disimpan di lokal (sql) tidak di simpan di firebase

**Comment by elrizwiraswara** [comment]
Hi [Adityadn64](https://github.com/Adityadn64),

Thank you for bringing this issue to my attention. I wanted to let you know that I have updated the code and fixed the issue in my latest commit.

Please pull the latest changes and let me know if you encounter any further issues. If everything is working as expected, I'll go ahead and close this issue.
