### ISSUE TITLE
Loading Bug

### ISSUE THREAD

**Issue by Adityadn64** [elrizwiraswara/flutter_pos#4]
Seluruh halaman mengalami loading bug yang dimana proses AppProgressIndicator masih dipanggil di seluruh halaman ini menunjukkan bahwa proses sedang mengambil data, tetapi kenapa lama sekali?

**Comment by elrizwiraswara** [comment]
Since it is using Firestore, it’s normal for the data retrieval to take longer, as Firestore can have a delay when requesting data from the server. The loading time can vary depending on the network conditions and the size of the data being fetched
